apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    k8s-app: calico-typha
  name: calico-typha
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-typha
